version: "3.8"

services:
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: app_backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5001:5001"

  frontend:
    build: ./frontend
    container_name: app_frontend
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  pgdata:
